apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-exporter.fullname" . }}
  labels:
    {{- include "redis-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "redis-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.redisExpertor.repository }}/redis_exporter:{{ .Values.redisExpertor.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.redisExpertor.pullPolicy }}
          env:
          - name: REDIS_ADDR
            value:  {{ .Values.redis.service }}:{{ .Values.redis.port }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - name: init-{{ .Chart.Name }}
          image: busybox:1.28
          command:
          - 'sh'
          - '-c'
          - |
            check_redis() {
              echo -e "PING\r\n" | nc -w 1 {{ .Values.redis.service }} {{ .Values.redis.port }} \
              | grep -q "+PONG"
            }

            until check_redis
            do
              echo "waiting for {{ .Values.redis.service }}"
              sleep 2
            done
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
