name: Bug Report
description: Create a bug report to help improve cloud-native-ai-pipeline
labels: kind/bug
body:
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: |
        Please provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner.
        If this matter is security related, please disclose it privately via our security contact.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How can we reproduce it (as minimally and precisely as possible)?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Anything else we need to know?

  - type: textarea
    id: pipelineVersion
    attributes:
      label: Cloud-Native AI Pipeline version commit
      value: |
        <details>

        ```console
        # Provide version details here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: kubernetesVersion
    attributes:
      label: Kubernetes version
      value: |
        <details>

        # Specify cloud provider or indicate if it's a bare metal deployment

        </details>
    validations:
      required: true

  - type: textarea
    id: osVersion
    attributes:
      label: OS version
      value: |
        <details>

        ```console
        $ cat /etc/os-release
        # paste output here
        $ uname -a
        # paste output here
        ```

        </details>
    validations:
      required: true

