{
 "title": "Cloud Native AI Pipeline",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Infer FPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "infer_fps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Drop FPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "drop_fps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Infer FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "sum(infer_fps)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Drop FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "sum by(container) (drop_fps)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Streaming to Inference Latency (Average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(streaming_to_inference_latency_sum[1m])\r\n  /\r\nrate(streaming_to_inference_latency_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference Latency (Average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(predict_latency_sum[1m])\r\n  /\r\nrate(predict_latency_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Streaming to Inference Latency (Quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(streaming_to_inference_latency_bucket[1m]))",
     "legendFormat": "p99 ({{pod}})"
    },
    {
     "expr": "histogram_quantile(0.95, rate(streaming_to_inference_latency_bucket[1m]))",
     "legendFormat": "p95 ({{pod}})"
    },
    {
     "expr": "histogram_quantile(0.90, rate(streaming_to_inference_latency_bucket[1m]))",
     "legendFormat": "p90 ({{pod}})"
    }
   ]
  },
  {
   "title": "Inference Latency (Quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(predict_latency_bucket[1m]))",
     "legendFormat": "p99 ({{pod}})"
    },
    {
     "expr": "histogram_quantile(0.95, rate(predict_latency_bucket[1m]))",
     "legendFormat": "p95 ({{pod}})"
    },
    {
     "expr": "histogram_quantile(0.90, rate(predict_latency_bucket[1m]))",
     "legendFormat": "p90 ({{pod}})"
    }
   ]
  }
 ]
}