name: Shell Code Scan

on:
  push:
    branches:
    - main
    paths:
    - '**/*.sh'
  pull_request:
    paths:
    - '**/*.sh'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  codescan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC1091
